impls: backend/zvms/impls
views: backend/zvms/views
template: web/src/apis/fApi-template.ts
apis: web/src/apis/fApi.ts

res:
  yaml: apis/res.yaml
  py: backend/zvms/res.py
  ts: web/src/apis/types/enums.ts

structs:
  py: backend/zvms/typing/structs.py
  ts: web/src/apis/types/structs.ts

rel-enums: ./enums
methods-flag:
  start: //--METHODS START----
  end: //--METHODS END----

# yaml跨行字符串的空格会没掉, 只能这么写
api-formatter: '\n  /**{}\n   * ### [{}] {}\n   * #### Authorization: {}{}\n   */\n  {}({}): ForegroundApiRunner<[]> {{\n    return createForegroundApiRunner({});\n  }}'
empty-formatter: "this, {}, {}{}"
object-formatter: '\n        this,\n        {},\n        {},\n        {}'

api-defaults:
  rule: /
  method: GET
  params: Any
  auth: ANY

