# 后端API的路径
views: backend/zvms/views
# 前端API模板的路径
template: web/src/apis/fApi-template.ts
# 前端API生成的路径
apis: web/src/apis/fApi.ts
# 文档的路径
doc: apis.md

# 资源文件(常量)的路径
res:
  yaml: apis/res.yaml
  py: backend/zvms/res.py
  ts: web/src/apis/types/enums.ts

# 结构体/参数校验器的路径
structs:
  py: backend/zvms/typing/structs.py
  ts: web/src/apis/types/structs.ts

rel-enums: ./enums
methods-flag:
  start: //--METHODS START----
  end: //--METHODS END----

# yaml跨行字符串的空格会没掉, 只能这么写
api-formatter: "\n  /**{}\n   * ### [{}] {}\n   * #### 权限: {}{}\n   */\n  {}({}): ForegroundApiRunner<{}> {{\n    return createForegroundApiRunner({});\n  }}"
doc-overall-header: "# 镇海中学义工管理系统文档\n"
doc-apis-header: "## API\n"
doc-struct-formatter: "### {}\n```json{}```\n"
doc-header-formatter: "### {}. {}\n"
doc-formatter: "#### {}.{} {} `{}`\n{}  \n权限: {}  \n请求方法: `{}`  \n参数: `{}`  \n返回值: `{}`  \n"
empty-formatter: "this, {}, {}{}"
object-formatter: "\n        this,\n        {},\n        {},\n        {}"
auth-needless: "不需要"

# 默认值
api-defaults:
  rule: /
  method: GET
  params: Any
  response: Any
  auth: ANY